apiVersion: apps/v1
kind: Deployment
metadata:
  name: is
spec:
  replicas: 1
  selector:
    matchLabels:
      app: is
  template:
    metadata:
      labels:
        app: is
    spec:
      containers:
        - name: is
          image: ghcr.io/dm20-consortium/dm2-is:v1.2.0
          ports:
            - name: tcp-9001
              containerPort: 9001
              protocol: TCP
            - name: udp-9002
              containerPort: 9002
              protocol: UDP
            - name: udp-55602
              containerPort: 55602
              protocol: UDP
          command:
            - /bin/sh
            - -c
            - |
                echo "Waiting for dependencies..."

                until getent hosts rdb-service; do
                    echo "Waiting for rdb-service..."
                    sleep 1
                done

                until getent hosts cs-service; do
                    echo "Waiting for cs-service..."
                    sleep 1
                done

                echo "Dependencies are ready."
                exec dm2is -d /var/dm2/conf
          volumeMounts:
            - name: is-conf
              mountPath: /var/dm2/conf
              readOnly: true
      volumes:
        - name: is-conf
          hostPath:
            path: /var/dm2/conf
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: is-service
spec:
  selector:
    app: is
  ports:
    - name: tcp-9001
      protocol: TCP
      port: 9001
      targetPort: 9001
    - name: udp-9002
      protocol: UDP
      port: 9002
      targetPort: 9002
    - name: udp-55602
      protocol: UDP
      port: 55602
      targetPort: 55602
  type: ClusterIP