# 自ノードのSID
MY_STATION_ID = 1901000001

# ネットワークインターフェース数（送信側）
SEND_NETWORK_NUM = 1
# ネットワークインターフェース数（受信側）
RECEIVE_NETWORK_NUM = 1

################### 下記は、SEND_NETWORK_NUM / RECEIVE_NETWORK_NUM の数だけ、設定する #############
## 送信・受信共通設定
# NIC名
INTERFACE_NAME_1 = ens5
# 送受信に使うプロコトルと暗号化の組合せ
#  - udp:           UDP(ユニキャスト, 暗号化なし)
#  - udp_etm:       UDP(ユニキャスト, 暗号化あり）
#  - udp_pki:       UDP(ユニキャスト, 暗号化・署名あり）
#  - udp_multicast: UDP(マルチキャスト)
#  - dtls:          DTLS
SOCKET_TYPE_1 = udp
# CS電文のサイズ（ヘッダ＋ペイロード）。超えた場合はCSの中で分割送信される。
CS_PACKET_SIZE_1 = 1442

## 送信用設定
# 送信する宛先のSIDとIPアドレスを記載したリスト。csvファイルのファイル名を指定する
SEND_LIST_1 = ./send_list_v4.csv

## 受信用設定
# IPアドレスのバージョン指定
INTERFACE_IP_VER_1 = 4
# UDPポート番号
UDP_PORT_NUMBER_1 = 55555

################### ここまで ######################################################################

#INTERFACE_NAME_2 = 
#SOCKET_TYPE_2 = 
#CS_PACKET_SIZE_2 = 
#INTERFACE_IP_VER_2 =
#UDP_PORT_NUMBER_2 = 

# 重複受信データ管理のレコード保持時間、及びデータ削除処理実行間隔(秒)
DUAL_MAP_CLEAR_TIME = 100
# sendto実行エラー発生時のsendtoリトライ回数
MAX_SENDTO_TIMES = 10
# 複数通信時の重複チェックフラグ(1:重複除去する、1以外:除去しない)
CS_DUPLICATE_CHECK = 1
# トレースログのON/OFF(OFF:0, ON:1)
TRACE_ON = 0
