# DB設定
# @DATABASE_NAME:接続先のDB名
DATABASE_NAME=dm2_db

# @DATABASE_IS_NAME:ISが取り扱うDB名
DATABASE_IS_NAME=dm2_is_db

# @DATABASE_ADDR:RDBのIPアドレス
DATABASE_ADDR=172.19.3.2

# @DATABASE_PORT:RDBのポート番号
DATABASE_PORT=5432

# @USER_NAME:DB接続時のユーザ名
USER_NAME=dm2

# @PASS:DB接続時のパスワード
DB_PASS=dm2rdbsamplepassword
