# logger
# @log4j.rootLogger:ログレベル、出力方法を指定
log4j.rootLogger=info, stdout, file
#log4j.debug=true

# stdout appender
# @log4j.appender.stdout:stdoutを出力するためのコンソールクラス指定
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
# @log4j.appender.stdout.Target:stdoutを出力するための出力先指定
log4j.appender.stdout.Target=System.out
# @log4j.appender.stdout.layout:stdoutを出力するためのパターンレイアウトクラス指定
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
# @log4j.appender.stdout.layout.ConversionPattern:stdoutを出力するためのフォーマットを指定
log4j.appender.stdout.layout.ConversionPattern=%d %t %5p %c{1} - %m%n

# file appender
# @log4j.appender.file:fileを出力するためのファイルクラス指定
log4j.appender.file=org.apache.log4j.RollingFileAppender
# @log4j.appender.file.File:fileを出力するための出力先指定
log4j.appender.file.File=/tmp/dm2is.log
# @log4j.appender.file.Apppend:fileを出力するための追加出力可否を指定
log4j.appender.file.Apppend=true
# @log4j.appender.file.layout:fileを出力するためのパターンレイアウトクラス指定
log4j.appender.file.layout=org.apache.log4j.PatternLayout
# @log4j.appender.file.layout.ConversionPattern:fileを出力するためのフォーマットを指定
log4j.appender.file.layout.ConversionPattern=%d %t %5p %c{1} - %m%n
log4j.appender.file.MaxFileSize=50MB
log4j.appender.file.MaxBackupIndex=10  #10ファイルまでログ保持
log4j.appender.file.DatePattern='.'yyyy-MM-dd

