ARG IMAGE_TAG=20.04
FROM ubuntu:${IMAGE_TAG}

# avoid hunging up
ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
  && apt-get install -y \
    wget \
    build-essential \
    cmake \
    python3-pip \
  && rm -rf /var/lib/apt/lists/*

# install protobuf
WORKDIR /
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protobuf-cpp-3.21.12.tar.gz && \
  tar zxvf protobuf-cpp-3.21.12.tar.gz && \
  rm protobuf-cpp-3.21.12.tar.gz
RUN mkdir protoc
WORKDIR /protobuf-3.21.12
RUN ./configure --prefix=/usr/local --enable-python
RUN pip install protobuf==3.20.3
RUN make -j4 && \
	make install && \
	rm -f \
		/usr/local/lib/libprotobuf.a \
		/usr/local/lib/libprotobuf-lite.a \
		/usr/local/lib/libprotoc.a \
		/usr/local/lib/libprotobuf.la \
		/usr/local/lib/libprotobuf-lite.la \
		/usr/local/lib/libprotoc.la \
		/usr/local/lib/libprotobuf-lite.so \
		/usr/local/lib/libprotobuf-lite.so.32 \
		/usr/local/lib/libprotobuf-lite.so.32.0.12 && \
	rm -rf /protobuf-3.21.12