MY_STATION_ID = 1721920
SEND_NETWORK_NUM = 1
RECEIVE_NETWORK_NUM = 1
INTERFACE_NAME_1 = eth1
INTERFACE_IP_VER_1 = 4
UDP_PORT_NUMBER_1 = 55555
SOCKET_TYPE_1 = 0
SEND_LIST_1 = ./send_list_v4.csv
CS_PACKET_SIZE_1 = 1442

DUAL_MAP_CLEAR_TIME = 100
MAX_SENDTO_TIMES = 10
CS_DUPLICATE_CHECK = 1
TRACE_ON = 0
APPLICATION_PROTOCOLS = "\x0ahq-interop\x05hq-29\x05hq-28\x05hq-27\x08http/0.9"
MAX_IDLE_TIMEOUT = 500000
MAX_RECV_UDP_PAYLOAD_SIZE = 1350
INITIAL_MAX_DATA = 10000000
INITIAL_MAX_STREAM_DATA_BIDI_LOCAL = 1000000
INITIAL_MAX_STREAM_DATA_BIDI_REMOTE = 1000000
INITIAL_MAX_STREAMS_BIDI = 100
CC_ALGORITHM = 0
CERT_PATH = cs_quic/cert.crt
KEY_PATH = cs_quic/cert.key

INITIAL_MAX_STREAM_DATA_UNI = 1000000
INITIAL_MAX_STREAMS_UNI = 100
DISABLE_ACTIVE_MIGRATION = 1
