name: Build and Push dm2-cs

on:
  workflow_dispatch:
    inputs:
      version:
        description: Docker image version
        required: true
        type: choice
        options:
          - v1.1.0
        default: v1.1.0

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.version }}

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build secLib
        run: |
          docker build \
            --build-arg IMAGE_TAG=20.04 \
            -t dm2/seclib:20.04 \
            ./secLib

      - name: Build csLib
        run: |
          docker build \
            --build-arg IMAGE_TAG=20.04 \
            -t dm2/cslib:20.04 \
            ./csLib

      - name: Build dm2-cs
        run: |
          docker build \
            --build-arg IMAGE_TAG=20.04 \
            -t ghcr.io/dm20-consortium/dm2-cs:${{ inputs.version }} \
            ./cs

      - name: Push dm2-cs
        run: |
          docker push ghcr.io/dm20-consortium/dm2-cs:${{ inputs.version }}