name: Build and Push dm2-cs

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build secLib
        working-directory: dm2
        run: |
          docker build \
            -f secLib/Dockerfile \
            --build-arg IMAGE_TAG=20.04 \
            -t dm2/seclib:20.04 \
            secLib/

      - name: Build csLib
        working-directory: dm2
        run: |
          docker build \
            -f csLib/Dockerfile \
            --build-arg IMAGE_TAG=20.04 \
            -t dm2/cslib:20.04 \
            csLib/

      # final image
      - name: Build dm2-cs
        working-directory: dm2
        run: |
          docker build \
            -f cs/Dockerfile \
            --build-arg IMAGE_TAG=20.04 \
            -t ghcr.io/dm20-consortium/dm2-cs:${{ github.ref_name }} \
            -t ghcr.io/dm20-consortium/dm2-cs:latest \
            ./

      - name: Push dm2-cs
        run: |
          docker push ghcr.io/dm20-consortium/dm2-cs:${{ github.ref_name }}
          docker push ghcr.io/dm20-consortium/dm2-cs:latest