CREATE TABLE operator_history (
	name			varchar NOT NULL,
	type			varchar NOT NULL, 
	ts				bigint NOT NULL,  
	pid				varchar NOT NULL,
	mng_id			int, 
	argument		varchar NOT NULL,
	proc_num		bigint NOT NULL, 
	last_buffer_size_long	bigint, 
	tupleNumSum		bigint NOT NULL, 
	tupleNumMin		bigint NOT NULL, 
	tupleNumMax		bigint NOT NULL, 
	tupleNumAvg		double precision,
	allTimeMin		double precision,
	allTimeMax		double precision,
	allTimeAvg		double precision,
	getTimeMin		double precision,
	getTimeMax		double precision,
	getTimeAvg		double precision,
	procTimeMin		double precision,
	procTimeMax		double precision,
	procTimeAvg		double precision,
	fireTimeMin		double precision,
	fireTimeMax		double precision,
	fireTimeAvg		double precision
);
